covidify/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('rapidTest.urls')),
    path('', include('qna.urls')),
    path('', include('list_rs.urls')),
    path('', include('health_protocol.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('feedbacks',views.listFeedback, name='feedbacklist'),
    path('formFeedback',views.formFeedback, name='feedbackform'),
    path('signup/', views.signUp, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dataFeedback/',views.api_feedback, name= 'dataFeedback'),
]

qna/urls.py
from django.urls import path

from . import views

app_name = 'qna'

urlpatterns = [
     path('qna/',views.forum,name='forum'),
     path('balas/<int:komen_id>/' ,views.balas, name='balas'),
     path('dataqna/', views.api_pertanyaan, name = 'dataqna'),
     path('datakomen/', views.api_komen, name = 'datakomen'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Feedback(models.Model):
    nama = models.CharField(max_length=100)
    feedbackUser = models.TextField(max_length=1000)
    
class Pengguna(models.Model):
    namalengkap = models.CharField(max_length=100)
    lokasi = models.CharField(max_length=100)
    pekerjaan = models.CharField(max_length=100)
    institusi = models.CharField(max_length=100)
    akun = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "{} | {} | {} | {}".format(self.namalengkap, self.lokasi, self.pekerjaan, self.institusi)

main/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class FeedbackForm(forms.ModelForm):
    nama = forms.CharField(label="Nama")
    feedbackUser = forms.CharField(widget=forms.Textarea, label='Feedback')
    class Meta:
        model = Feedback
        fields = '__all__'
    
class SignUpForm(UserCreationForm):
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'type' : 'password',
                'placeholder': 'Enter your password',
                'name': 'password',
            }
        )
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'type' : 'password',
                'placeholder': 'Confirm your password',
                'name': 'password',
            }
        )
    )
    class Meta :
        model = User
        fields= ("email",'username')
        labels = {'username':'Username','email':'Email',}
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control','placeholder': "Enter your username here",  "autocomplete":"off"}),
            'email': forms.TextInput(attrs={'class':'form-control','placeholder': "Enter your email here",  "autocomplete":"off"}),
        }
        help_texts = {
            "username":None,
        }

class PenggunaForm(forms.ModelForm):
    class Meta :
        model = Pengguna
        fields =['namalengkap','lokasi','institusi','pekerjaan']
        labels = {'lokasi':'Lokasi','institusi':'Institusi','pekerjaan':'Pekerjaan','namalengkap':"Nama Lengkap"}
        widgets ={
            'lokasi': forms.TextInput(attrs={'class':'form-control','placeholder': "Enter your location here"}),
            'institusi': forms.TextInput(attrs={'class':'form-control','placeholder': "Enter your institution here"}),
            'pekerjaan': forms.TextInput(attrs={'class':'form-control','placeholder': "Enter your work here"}),
            'namalengkap': forms.TextInput(attrs={'class':'form-control','placeholder': "Enter your full name here"})}

class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username",
    widget=forms.TextInput(
        attrs={
        'class' : 'form-control',
        'placeholder' : 'Username',
        'type' : 'text',
        'name': 'username',
    }))

    password = forms.CharField(label="Password", 
    widget=forms.PasswordInput(
        attrs={
        'class' : 'form-control',
        'placeholder' : 'Password',
        'type' : 'password',
        'name': 'password',
    }))

main/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
import requests
import json
from .models import *
from .forms import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core import serializers

def home(request):
    url = "https://covid-193.p.rapidapi.com/statistics"
    querystring = {"country":"Indonesia"}
    headers = {
        'x-rapidapi-host': "covid-193.p.rapidapi.com",
        'x-rapidapi-key': "7b039c71a9msh11121f885beb4e5p15166bjsn0807437126b5"
        }
    response = requests.request("GET", url, headers=headers, params=querystring).json()
    data = response['response']
    d =data[0]
    # print(d)
    context = {
        'all' : d['cases']['total'],
        'recovered' : d['cases']['recovered']
    }
    return render(request, 'main/home.html',context)

def formFeedback(request):
    form = FeedbackForm()
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/feedbacks')
    context = {
        'form' : form,
    }
    return render(request, 'main/feedbackForm.html',context)
    
# @login_required(login_url="main:login")
def listFeedback(request):
    feedbacks = Feedback.objects.all()
    return render (request,'main/feedbackList.html',{'feedbacks':feedbacks})

def signUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        form2 = PenggunaForm(request.POST)
        userModel = Pengguna.objects.all()

        if form.is_valid() and form2.is_valid():
            user = form.save()
            userModel.create(
                namalengkap = form2.cleaned_data.get('namalengkap'),
                lokasi = form2.cleaned_data.get('lokasi'),
                institusi = form2.cleaned_data.get('institusi'),
                pekerjaan = form2.cleaned_data.get('pekerjaan'),
                akun = user
            )
            login(request, user)
            return HttpResponseRedirect('/')

        else:
            for msg in form.error_messages:
                messages.error(request, 'Invalid entry')

    else:
        form = SignUpForm()
        form2 = PenggunaForm()

    context = {
        'form' : form,
        'form2':form2,
    }

    return render(request, "main/signup.html", context)
    
def login_view(request):
    if request.method == 'POST':
        valuenext = request.POST.get('next')
        form = LoginForm(data = request.POST)

        if form.is_valid():
            usernameInput = request.POST["username"]
            passwordInput = request.POST["password"]

            user = authenticate(request, username=usernameInput, password=passwordInput)

            if user is not None and valuenext == "":
                login(request, user)
                return redirect('main:home')
            if user is not None and valuenext != "":
                login(request, user)
                return redirect(valuenext)
        else:
            messages.error(request, 'Invalid entry')

    else:
        form = LoginForm()

    context = {
        'form' : form,
    }

    return render(request, 'main/login.html', context)

@login_required
def logout_view(request):
    logout(request)
    form = LoginForm()
    response = {
        'form' : form,
    }
    return redirect('main:login')

def api_feedback(request):
    rs = Feedback.objects.all()
    json_feedback = serializers.serialize('json', rs)
    return HttpResponse(json_feedback, content_type="text/json-comment-filtered")

main/templates/main/feedbackForm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block meta %}
<header>
    <link rel="stylesheet" href="{% static 'css/homefeed.css' %}"/>
    <div class="cover2" >
    </div>
</header>
{% endblock meta %}

{% block content %}
<div class="container" style="margin-top: 50px; margin-bottom: 200px;">
    <div class="container-fluid">
            <h2 class="featurette-heading" style="color: #2C175D;"><b>Give Us Your Feedback</b></h2>
            <hr class="mt-0 mb-4">
            <form method='POST'>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn" style="background-color: #2C175D; color: white;" ><b>Submit</b></button>
            <a type="button" class="btn btn-danger" href="{% url 'main:home' %}"><b>Back</b></a>
        </form>
    </div>
</div>

{% endblock content %}

main/templates/main/feedbackList.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block meta %}
<header>
    <link rel="stylesheet" href="{% static 'css/homefeed.css' %}"/>
    <div class="cover2" >
    </div>
</header>
{% endblock meta %}

{% block content %}
  <div class="container feedbackss" style="margin-top: 50px; margin-bottom: 200px;">
    <div class="container-fluid">
        <div class="d-flex bd-highlight mb-3">
          <div class="p-2 bd-highlight">
                <h2 class="featurette-heading" style="color: #2C175D;"><b>Give Us Your Feedback</b></h2>
              </div>
              {% if user.is_authenticated %}
              <div class= "container-fluid text-right" style="margin-bottom: 100px;">
                <a id = "but" class="btn btn-primary btn-lg" 
                style= "background-color: #232065"
                href="{% url 'main:feedbackform'  %}" 
                role="button">Add Feedback</a>
              </div>
              {% else %}
              <div class= "container-fluid text-right" style="margin-bottom: 100px;">
                <a id = "but" class="btn btn-primary btn-lg"
                onClick="alert('Anda belum login, silakan login terlebih dahulu')"
                style= "background-color: #232065"
                href="{% url 'main:login'  %}" 
                role="button">Add Feedback</a>
              </div>
              {% endif %}
            </div>
            
            <hr class="mt-0 mb-4">
            <section id="isi">
          
            </section>
          </div>
        </div>
        
      <script>
        $("#but").on("mouseenter", function(){
            $(this).css("background-color", "#DCCFEE");
            $(this).css("color","#262833");
        });

        $("#but").on("mouseleave", function(){
            $(this).css("background-color", "#232065");
            $(this).css("color","#FFFFFF");
        });

        
        
        $.ajax({
            url: "/dataFeedback",
            success: function(data) {
              console.log(data)
              for (var i = 0 ; i < data.length ; i++) {
                var obj = data[i]
                
                console.log("masuk")
                var result = '<div class="card text-white" id = "kartu" style="background-color: #2C175D; margin-top: 20px; border-radius: 10px;">' +
                  '<div class="card-header border-bottom border-light"><b>' + obj.fields.nama + '</b></div>' +
                  '<div class="card-body">' + '<p class="card-text">' + obj.fields.feedbackUser + '</p>' + '</div>' + '</div'
                  $('#isi').append(result);
                  
                }
              }
            });
      </script>
      <script>
        $("label.switch").click(function() {
          $("body").toggleClass("dark-bg")
          // $("p").slideToggle("light-text")
          $("h2").toggleClass("light-font")
      })
      </script>

{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}

<header> 
  <link rel="stylesheet" href="{% static 'css/homefeed.css' %}"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"></script>
  <div class="cover" style="background-image: url(static/image/tst.png);">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <img src="{% static 'image/Group19.png' %}" class="img-fluid" alt="Responsive image" style="width: 10500px;">
        </div>
        <div class="col-md-6">
          <p id="pertama">LET’S HELP  RECOVER THE EARTH</p>
          <p id="kedua">SAVE YOURSELF, SAVE THE WORLD</p>
          <p id="ketiga">Coronavirus disease (COVID-19) is an infectious disease caused by a new virus</p>
          <div class="d-flex justify-content-start">
            <div class="tombol">
              <a href="https://www.youtube.com/watch?v=0dAoCfgAQw8" class="btn btn-danger mr-3 btn-lg" >Watch Here</a>
              <a href="https://www.youtube.com/watch?v=0dAoCfgAQw8" class="btn btn-outline-warning btn-lg">Learn More</a>
            </div>
          </div>
          <div class="d-flex justify-content-start" style="margin-top: 20px;">
            <div class="card text-center mr-4 " id="kartu" style="width: 18rem; background-color: #4029BB; border-radius: 20px; box-shadow: 3px 6px rgba(0, 0, 0, 0.3);">
              <div class="card-body">
                <p id="kelima" >Active</p>
                <h1 id="keenam">{{ all }}</h1>
              </div>
            </div>
            <div class="card text-center" id="kartu" style="width: 18rem; background-color: #4029BB; border-radius: 20px; box-shadow: 3px 6px rgba(0, 0, 0, 0.3);">
              <div class="card-body">
                <p id="kelima">Recovered</p>
                <b id="ketujuh">{{ recovered }}</b>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock meta %}

{% block content %}
<div class="container">
  <div class="container-fluid">
    <div class="row">
      <div class="row flex-row-reverse">
        <div class="col-md-6">
            <img src="{% static 'image/Group38.png' %}" class="img-fluid" alt="Responsive image" >
        </div>
        <div class="col-md-6 ">
          <p id="first">Apa Itu COVID-19?</p>
          <p id="second">Penyakit yang disebabkan oleh virus severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2).</p>
        </div>
      </div>
        <div class="col-md-6" >
          <img src="{% static 'image/Group35.png' %}" class="img-fluid" alt="Responsive image" >
        </div>
        <div class="col-md-6">
          <p id="first">Gejala umum Covid19 apa saja?</p>
          <p id="second">
            Gejala umumnya demam (suhu tubuh diatas 38°C), batuk kering,
            dan sesak napas</p>
        </div>
        <div class="row flex-row-reverse">
          <div class="col-md-6" >
            <img src="{% static 'image/Group46.png' %}" class="img-fluid" alt="Responsive image">
          </div>
          <div class="col-md-6" >
            <p id="first">Apa lagi gejala Covid19 yang lain ?</p>
            <p id="second">Gejala lainnya mudah lelah, nyeri otot, nyeri dada, sakit tenggorokan, sakit kepala, mual / muntah, diare, hingga hilangnya kemampuan mengecap rasa / mencium bau.</p>
          </div>
        </div>
      <div class="col-md-6" >
          <img src="{% static 'image/Group36.png' %}" class="img-fluid" alt="Responsive image">
      </div>
      <div class="col-md-6">
        <p id="first">Apakah ada faktor risiko Covid-19?</p>
        <p id="second">
          Covid19 dapat menyerang siapa saja, tetapi akan lebih berbahaya/bahkan fatal jika menyerang orang lanjut usia, ibu hamil, perokok, dan orang dengan imun lemah.</p>
      </div>
      <div class="row flex-row-reverse" style="margin-bottom: 100px;">
        <div class="col-md-6">
            <img src="{% static 'image/Group40.png' %}" class="img-fluid" alt="Responsive image">
        </div>
        <div class="col-md-6">
          <p id="first">Pemeriksaan apa yang harus saya lakukan?</p>
          <p id="second">Rapid test, Tes PCR (polymerase chain reaction) / swab test, CT Scan, atau tes darah lengkap.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $("label.switch").click(function() {
    $("p").toggleClass("light-font")
    $("body").toggleClass("dark-bg")
  })
  $("#keenam").counterUp({delay:30, time:2000})
  $("#ketujuh").counterUp({delay:30, time:500})
</script>
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}
  
{% block content %}

<div class="container-fluid">
    <div class = "row">
        <div class="col-sm-12">
            <h2 class="text-center" style="margin-top: 20px;"><b>Let's Log In First, Shall We?</b></h2>
            <br>
            <br>
            <div class="col d-flex justify-content-center ">
                <div class="card " style="width: 50rem;">
                    <div class="card-header" style="background-color: #232065;">
                        <p style="text-align: center; font-weight: bolder; color: white; font-size: larger;">LOG IN</p>
                    </div>
                    <div class="card-body">
                        <form class="align-self-center" action="" method="POST">
                            {% csrf_token %}
                            {{ form }}
                            <br>
                            <input type="hidden" name="next" value="{{ request.GET.next }}"/>
                            <button style= "background-color: #232065" type="submit" class="btn btn-primary btn-m">Login</button>
                        </form>
                        <p style="margin-top: 10px;">
                            Don't have an account yet? <a class="sign-up-in-link" href="{% url 'main:signup' %}"><strong>Sign up.</strong></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/main/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}

<div class="container-fluid">
    <div class = "row">
        <div class="col-sm-12">
            <h2 class="text-center" style="margin-top: 20px;"><b>Join Us!</b></h2>
            <br>
            <br>
            <div class="col d-flex justify-content-center">
                <div class="card " style="width: 50rem;">
                    <div class="card-header" style="background-color: #232065;">
                        <p style="text-align: center; font-weight: bolder; color: white; font-size: larger;">SIGN UP</p>
                    </div>
                    <div class="card-body">
                        <form class="align-self-center" action="" method="POST">
                            {% csrf_token %}
                            {{ form2 }}
                            {{ form }}
                            <br>
                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                            <button style= "background-color: #232065" type="submit" class="btn btn-primary btn-m">Sign Up</button>
                        </form>
                        <p style="margin-top: 10px;">
                            Already have an existing account? <a class="sign-up-in-link" href="{% url 'main:login' %}"><strong>Log in.</strong></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<br>

{% endblock content %}