covidify/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('rapidTest.urls')),
    path('', include('qna.urls')),
    path('', include('list_rs.urls')),
    path('', include('health_protocol.urls')),
]

list_rs/urls.py
from django.urls import path
from .views import tambahRS, listRS, api_rs
app_name = 'list_rs'
urlpatterns = [
    path('tambahRS/',tambahRS, name='tambahRS'),
    path('listRS/',listRS,name = 'listRS'),
    path('data/', api_rs, name = 'data'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('feedbacks',views.listFeedback, name='feedbacklist'),
    path('formFeedback',views.formFeedback, name='feedbackform'),
    path('signup/', views.signUp, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dataFeedback/',views.api_feedback, name= 'dataFeedback'),
]

qna/urls.py
from django.urls import path

from . import views

app_name = 'qna'

urlpatterns = [
     path('qna/',views.forum,name='forum'),
     path('balas/<int:komen_id>/' ,views.balas, name='balas'),
     path('dataqna/', views.api_pertanyaan, name = 'dataqna'),
     path('datakomen/', views.api_komen, name = 'datakomen'),
]

list_rs/models.py
from django.db import models

class Rumah_Sakit(models.Model):
    provinsi = models.CharField(max_length=100)
    nama_rs = models.CharField(max_length=100)
    alamat = models.CharField(max_length=1000)
    telepon = models.IntegerField()
    website = models.CharField(max_length=1000)

list_rs/forms.py
from django import forms
from .models import Rumah_Sakit

class Form_RS(forms.Form):
    provinsi = forms.CharField(label = "Nama Provinsi", 
                                max_length = 100, 
                                widget = forms.TextInput(attrs={
                                "placeholder": "Ex : DKI Jakarta", 
                                "class":"form-control",}))

    nama_rs = forms.CharField(label = "Nama Rumah Sakit", 
                                max_length = 100, 
                                widget = forms.TextInput(attrs={
                                "placeholder": "Ex : RSPI Prof. Dr. Sulianti Saroso", 
                                "class":"form-control",}))

    alamat = forms.CharField(label = "Alamat Rumah Sakit", 
                                max_length = 1000, 
                                widget = forms.TextInput(attrs={ 
                                "class":"form-control",}))

    telepon = forms.IntegerField(label = "No. Telepon Rumah Sakit",  
                                widget = forms.NumberInput(attrs={
                                "placeholder": "Ex : 021-6506559", 
                                "class":"form-control",
                                }))

    website = forms.CharField(label = "Website Rumah Sakit", 
                                max_length = 1000, 
                                widget = forms.TextInput(attrs={
                                "placeholder": "Ex : https://rspi-suliantisaroso.com/", 
                                "class":"form-control",}))
    
    

list_rs/views.py
from django.shortcuts import render, redirect
from .models import Rumah_Sakit
from .forms import Form_RS
from django.core import serializers
from django.http import HttpResponse

def tambahRS(request):
    form = Form_RS() #data dari form
    if request.method == "POST":
        input_form = Form_RS(request.POST)
        if input_form.is_valid():
            data = input_form.cleaned_data #datanya masuk ke dict cleaned_data, karna pas di cek dia udah valid
            input_rs = Rumah_Sakit() #panggil class di models

            input_rs.provinsi = data['provinsi'] #buat key value, data itu nama dict nya
            input_rs.nama_rs = data['nama_rs']
            input_rs.alamat = data['alamat']
            input_rs.telepon = data['telepon']
            input_rs.website = data['website']

            input_rs.save()
            data_terbaru = Rumah_Sakit.objects.all()

            return redirect('/listRS')
    else:
        rs = Rumah_Sakit.objects.all()
        context = {'form':form,'rs':rs}
        return render(request, 'list_rs/tambah_rs.html', context)

def listRS(request):
    all_data = Rumah_Sakit.objects.all()
    return render(request, 'list_rs/list_rs.html', {'ListRs':all_data})

def api_rs(request):
    rs = Rumah_Sakit.objects.all()
    json_rs = serializers.serialize('json', rs)
    return HttpResponse(json_rs, content_type="text/json-comment-filtered")

list_rs/templates/list_rs/list_rs.html
{% extends 'base.html'%}
{% load static %}


{% block content %}
<header>
    <link rel="stylesheet" href="{% static 'css/listRs.css' %}"/>
</header>
<div class = "cover_list">
    <h1>Daftar Rumah Sakit</h1>
</div>
<br>
<br>

<script>
    $(document).ready( function () {
        $('#list_rs').DataTable({
            "aLengthMenu":[[3, 5, 10, 25], [3, 5, 10, 25]],
                "iDisplayLength":3,
                "ordering" : false

        });

        $("#but").on("mouseenter", function(){
            $(this).css("background-color", "#DCCFEE");
        });

        $("#but").on("mouseleave", function(){
            $(this).css("background-color", "#232065");
        });

        $.ajax({
            url: "/data",
            success: function(data) {
                console.log("test")
                console.log(data)
                $('#isi').html('')
                var result = '<tr>';
                for(var i = 0; i < data.length; i++) {
                    var obj = data[i];
                    console.log("ini obj =" + obj)
                    result += "<tr>"+
                    "<td>" + obj.fields.provinsi + "</td>" +
                    "<td>" + obj.fields.nama_rs + "</td>" +
                    "<td>" + obj.fields.alamat+ "</td>" +
                    "<td>" + obj.fields.telepon + "</td>"+
                    "<td> <a id = 'web' class='btn btn-primary' style = 'background-color:#DCCFEE' href='" + 
                    obj.fields.website + "' target= '_blank' role='button'>Website</a> </td>"
                                
                }
                $('#isi').append(result);
            }
        })
        

    } );
</script>

<section> 
    <div class="container-fluid">
        <div class = "row">
            <div class="col-sm-12">
                <h2 class="text-center"> DAFTAR RUMAH SAKIT </h2>
                <br>
                <br>
                <div class="table-responsive-md">
                    <table id="list_rs" class="table table-striped">

                        <thead style="background-color:#222159;">
                        <tr style="color:#FFFFFF">
                        <th scope="col">Provinsi</th>
                        <th scope="col">Nama RS</th>
                        <th scope="col">Alamat</th>
                        <th scope="col">No. Telepon</th>
                        <th scope="col">Website</th>
                        </tr>
                        </thead>

                        <tbody id = "isi">
                        </tbody>
                    </table>
                </div>
                <br>
                {% if user.is_authenticated %}
                <div class= "container-fluid text-right" style="margin-bottom: 100px;">
                <a id = "but" class="btn btn-primary btn-lg" 
                    style= "background-color: #232065"
                    href="{% url 'list_rs:tambahRS'  %}" 
                    role="button">Add</a>
                </div>
                {% else %}
                <div class= "container-fluid text-right" style="margin-bottom: 100px;">
                <a id = "but" class="btn btn-primary btn-lg"
                    onClick="alert('Anda belum login, silakan login terlebih dahulu')"
                    style= "background-color: #232065"
                    href="{% url 'main:login'  %}" 
                    role="button">Add</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

list_rs/templates/list_rs/tambah_rs.html
{% extends 'base.html'%}
{% load static %}


{% block content %}
<header>
    <link rel="stylesheet" href="{% static 'css/listRs.css' %}"/>
</header>
<div class="cover_tambah">
    
</div>
<br>
<br>
<h2 style = "text-align:center">TAMBAH RUJUKAN RS</h2>

<section>
        <div class="container-fluid ">
            <div class = "row">
                <div class="col-sm-12 d-flex justify-content-center" style = "text-align:center">
                    <div class="card" style="width: 30rem; background-color:#FFFFFF">
                        <div class="card-header">
                            <div class="card-body">
                        
                                <form method='POST' class='d-flex justify-content-center'>
                                    <div class="form-row align-items-center">
                                        <div class="col-auto">
                                            {% csrf_token %}
                                            {{ form }}
                                            <br>
                                            <button style= "background-color: #232065" type="submit" class="btn btn-primary btn-lg">Add</button>
                                        </div>
                                    </div>
                                </form>

                                <!--button untuk ke list rumah sakit-->
                                <br>
                                
                                <a class="btn btn-primary btn-lg" 
                                style= "background-color: #232065"
                                href="{% url 'list_rs:listRS'  %}" 
                                role="button">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
{% endblock content %}